name: Build and Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      matrix:
        elixir: ["1.13.4", "1.14.4", "1.15.7", "1.16.0"]
        otp: ["24.3.4", "25.3.2", "26.2.1"]
        exclude:
          # Elixir 1.13 doesn't support the latest OTP
          - elixir: "1.13.4"
            otp: "26.2.1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          build-flags: --all-warnings --warnings-as-errors

      - name: Run Tests
        run: mix coveralls.json --warnings-as-errors
        if: always()

      # Optional, but Codecov has a bot that will comment on your PR with per-file
      # coverage deltas.
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./cover/excoveralls.json
