name: Build and Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      matrix:
        elixir: ["1.10.4", "1.11.4", "1.12.3", "1.13.4", "1.14.4", "1.15.7", "1.16.0"]
        otp: ["22.3", "23.3.4", "24.3.4", "25.3.2", "26.2.1"]
        exclude:
          # Elixir 1.10 only supports up to OTP 23
          - elixir: "1.10.4"
            otp: "26.2.1"
          - elixir: "1.10.4"
            otp: "25.3.2"
          - elixir: "1.10.4"
            otp: "24.3.4"
          # Elixir 1.11 doesn't support the latest OTP
          - elixir: "1.11.4"
            otp: "25.3.2"
          - elixir: "1.11.4"
            otp: "26.0.2"
          # Elixir 1.12 doesn't support the latest OTP
          - elixir: "1.12.3"
            otp: "25.3.2"
          - elixir: "1.12.3"
            otp: "26.0.2"
          # Elixir 1.13 doesn't support the latest OTP
          - elixir: "1.13.4"
            otp: "26.0.2"
          # Elixir 1.14 requires at least OTP 23
          - elixir: "1.14.4"
            otp: "22.3"
          # Elixir 1.15 requires at least OTP 24
          - elixir: "1.15.5"
            otp: "22.3"
          - elixir: "1.15.7"
            otp: "23.3.4"
          # Elixir 1.16 requires at least OTP 24
          - elixir: "1.16.0"
            otp: "22.3"
          - elixir: "1.15.5"
            otp: "23.3.4"

    # Remove if you don't need a database
    services:
      db:
        image: postgis/postgis:13-3.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: server_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          build-flags: --all-warnings --warnings-as-errors

      - name: Run Tests
        run: mix coveralls.json --warnings-as-errors
        if: always()

      # Optional, but Codecov has a bot that will comment on your PR with per-file
      # coverage deltas.
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./cover/excoveralls.json
